apiVersion: v1
kind: Service
metadata:
  name: grievance-api-prod-grievances
  namespace: pgrs-prod
spec:
  type: NodePort
  selector:
    app: grievance-api-prod-grievances
  ports:
    - port: 10000
      targetPort: 10000
      nodePort: 30200
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: grievance-api-prod-grievances
  namespace: pgrs-prod
spec:
  selector:
    matchLabels:
      app: grievance-api-prod-grievances
  replicas: 2
  template:
    metadata:
      labels:
        app: grievance-api-prod-grievances
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: host
                operator: In
                values:
                - node1
      tolerations:
      - key: "special"
        operator: "Equal"
        value: "true"
        effect: "PreferNoSchedule"    
      containers:
      - name: grievance-api-prod-grievances
        image: jfrog.local.com/grievances/grievances:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 10000
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:10000"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: BLOB_NAME
          value: "punjabeaprodstorage"
        - name: BLOB_KEY
          value: "KHD6xixPCvrc+L6qJqJoiV7PDIDaThnhAk709UbgXDMPDdIUyhS1LBnMVR5Z05PQbo17OcTowPIki3RpJa0U6A=="
        - name: TZ
          value: "Asia/Kolkata"
      imagePullSecrets:
        - name: jfrog.artifactory
  strategy:
    type: RollingUpdate 
    rollingUpdate:
         maxUnavailable: 25%
         maxSurge: 1 